# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "3306:3319"
        environment:
            - MYSQL_ROOT_PASSWORD=password123
            - MYSQL_DATABASE=diploma_khai
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=password123
        volumes:
            - ./server-side:/docker-entrypoint-initdb.d
    app:
        container_name: myapp
        links:
            - "db"
        build: ./
        ports:
            - "65432:65432"