

LOGIN_PAGE = {
    "login_label": {"EN": "Login (mail)", "UA": "Увійти (пошта)"},
    "auth_label": {"EN": "Authorization", "UA": "Авторизація"},
    "password_label": {"EN": "Password", "UA": "Пароль"},
    "login_button": {"EN": "Login", "UA": "Увійти"},
    "forgot_password_label": {"EN": "Forgot password?", "UA": "Забули пароль?"},
    "new_user_label": {"EN": "New user?", "UA": "Новий користувач?"},
    "registration_button": {"EN": "Registration", "UA": "Реєстрація"},
    "mail_label": {"EN": "Email", "UA": "Електронна пошта"},
    "password_repeat_label": {"EN": "Password confirmation", "UA": "Підтвердження паролю"},
    "confirmation_code_label": {"EN": "Confirmation code", "UA": "Код підтвердження"},
    "return_button": {"EN": "Back", "UA": "Назад"},
    "send_confirm_code": {"EN": "Send confirmation code", "UA": "Надіслати код підтвердження"},
    "wrong_email_label": {"EN": "Wrong format!", "UA": "Неправильний формат!"},
    "password_nomatch_label": {"EN": "Passwords are different!", "UA": "Паролі відрізняються!"},
    "wrong_confirmation_code_label": {"EN": "Wrong code!", "UA": "Неправильний код!"},
}

MAIN_WINDOW = {
    "": {"EN": "Main page", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
    "": {"EN": "", "UA": ""},
}